const ASADO_WORDS = [
  "choripan", "morcilla", "bondiola", "provoleta", "vacio",
  "entrania", "asador", "parrilla", "chimichurri", "criolla",
  "carbon", "lenia", "brasa", "tira", "costilla",
  "mollejas", "chinchulin", "rinion", "matambre", "colita",
  "achura", "chorizo", "entraña", "pampa", "gaucho",
  "fogon", "parilla", "salmuera", "adobo", "pincho",
  "espeto", "churro", "empanada", "locro", "humita",
  "tamale", "dulce", "torta", "alfajor", "factura",
  "medialuna", "bizcochito", "fernet", "mate", "bombilla",
  "termo", "asadito", "costillar", "lechon", "cordero",
  "cabrito", "pollo", "bife", "lomo", "picanha",
  "churrasco", "milanesa", "fugazza", "pizza", "faina",
  "morron", "cebolla", "tomate", "lechuga", "papa",
  "batata", "choclo", "zapallo", "acelga", "panceta",
  "tocino", "jamon", "queso", "manteca", "aceite",
  "vinagre", "limon", "naranja", "pomelo", "sidra",
  "vino", "cerveza", "soda", "gaseosa", "jugo",
  "helado", "postre", "fruta", "sandia", "melon",
  "durazno", "ciruela", "cereza", "mandarina", "banana",
  "manzana", "pera", "uva", "higo", "nuez",
  "almendra", "avellana", "castania", "garbanzo", "lenteja",
  "poroto", "arroz", "fideo", "raviole", "sorrentino",
  "noqui", "canelone", "lasaña", "tuco", "estofado",
  "guiso", "puchero", "carbonada", "revuelto", "tortilla",
  "picada", "tabla", "morfi", "birra", "escabio",
  "asadazo", "parrillada", "salamín", "longaniza", "butifarra",
  "mondongo", "tripa", "criadilla", "lengua", "corazon",
  "higado", "choripa", "chori", "pampeano", "criollo",
  "campero", "estancia", "rancho", "quincho", "terraza",
  "balcon", "patio", "jardin", "pileta", "cancha",
  "futbol", "pelota", "gol", "gambeta", "rabona",
  "caño", "tijera", "volea", "chilena", "cabezazo",
  "penal", "corner", "lateral", "arquero", "delantero",
];

export function generateSecretWord(): string {
  return ASADO_WORDS[Math.floor(Math.random() * ASADO_WORDS.length)];
}
